# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Pe√±a <jorge.israel.p@gmail.com>"]

[profile.dev]
rpath = true
# opt-level = 3
# debug = false
# lto = false
# debug-assertions = false

[dependencies]
glob = "*"
regex = "*"
regex_macros = "*"
log = "*"
env_logger = "*"
hoedown = "*"
rustc-serialize = "*"
docopt = "*"
toml = "*"
notify = "*"
libc = "*"
time = "*"
threadpool = "*"
tempdir = "*"
num_cpus = "*"
iron = "*"
staticfile = "*"
mount = "*"
chrono = "*"
zmq = "*"
websocket = "*"
git2 = "*"
handlebars = "*"
# anymap = "*"

[dependencies.anymap]
path = "../anymap"
# git = "https://github.com/chris-morgan/anymap.git"
# branch = "clone"
