# http://crates.io/manifest.html

[package]
name = "diecast"
version = "0.0.1"
authors = ["Jorge Israel Pe√±a <jorge.israel.p@gmail.com>"]

[profile.dev]
rpath = true
# opt-level = 3
# debug = false
# lto = false
# debug-assertions = false

[dependencies]
clippy = {version = "*", optional = true}

glob = "*"
regex = "*"
log = "*"
docopt = "*"
walker = "*"

time = "*"

# for Diecast.toml
toml = "*"

futures = "*"
futures-cpupool = "*"

threadpool = "*"
num_cpus = "*"

crossbeam = "0.2.10"
scoped_threadpool = "0.1.7"

typemap = "*"
rustc-serialize = "*"

# future deps
ansi_term = "*"
# rustbox = "*"
# ncurses = "*"
syncbox = "*"
eventual = "*"

[features]
default = []
